# Generated by Django 5.1.6 on 2026-04-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStorageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('backend', models.CharField(choices=[('local', '本机服务器'), ('s3', 'S3 对象存储'), ('webdav', 'WebDAV')], default='local', max_length=20)),
                ('local_subdir', models.CharField(default='uploads', max_length=200)),
                ('local_base_url', models.CharField(blank=True, default='', max_length=300)),
                ('s3_endpoint_url', models.CharField(blank=True, default='', max_length=500)),
                ('s3_region', models.CharField(blank=True, default='', max_length=100)),
                ('s3_bucket', models.CharField(blank=True, default='', max_length=200)),
                ('s3_access_key', models.CharField(blank=True, default='', max_length=200)),
                ('s3_secret_key', models.CharField(blank=True, default='', max_length=200)),
                ('s3_base_url', models.CharField(blank=True, default='', max_length=500)),
                ('webdav_base_url', models.CharField(blank=True, default='', max_length=500)),
                ('webdav_username', models.CharField(blank=True, default='', max_length=200)),
                ('webdav_password', models.CharField(blank=True, default='', max_length=200)),
                ('webdav_upload_path', models.CharField(blank=True, default='uploads/', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统存储配置',
                'verbose_name_plural': '系统存储配置',
            },
        ),
    ]
