# Generated by Django 5.1.6 on 2026-04-15 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_date', models.DateField(verbose_name='交班日期')),
                ('elective_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='择期手术数')),
                ('emergency_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='急诊手术数')),
                ('rescue_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='抢救手术数')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('other_incidents', models.TextField(blank=True, default='', verbose_name='其他事件')),
                ('specimen_handover_status', models.CharField(blank=True, choices=[('yes', '√'), ('no', '×'), ('other', '其他')], default='', max_length=10, verbose_name='标本交接状态')),
                ('specimen_handover_note', models.CharField(blank=True, default='', max_length=300, verbose_name='标本交接说明')),
                ('laminar_flow_running_status', models.CharField(blank=True, choices=[('yes', '√'), ('no', '×'), ('other', '其他')], default='', max_length=10, verbose_name='层流运行状态')),
                ('laminar_flow_running_note', models.CharField(blank=True, default='', max_length=300, verbose_name='层流运行说明')),
                ('bio_monitoring_status', models.CharField(blank=True, choices=[('yes', '√'), ('no', '×'), ('other', '其他')], default='', max_length=10, verbose_name='生物监测状态')),
                ('bio_monitoring_note', models.CharField(blank=True, default='', max_length=300, verbose_name='生物监测说明')),
                ('crash_cart_status', models.CharField(blank=True, choices=[('yes', '√'), ('no', '×'), ('other', '其他')], default='', max_length=10, verbose_name='急救车状态')),
                ('crash_cart_note', models.CharField(blank=True, default='', max_length=300, verbose_name='急救车说明')),
                ('fire_safety_status', models.CharField(blank=True, choices=[('yes', '√'), ('no', '×'), ('other', '其他')], default='', max_length=10, verbose_name='消防安全状态')),
                ('fire_safety_note', models.CharField(blank=True, default='', max_length=300, verbose_name='消防安全说明')),
                ('key_management_status', models.CharField(blank=True, choices=[('yes', '√'), ('no', '×'), ('other', '其他')], default='', max_length=10, verbose_name='钥匙管理状态')),
                ('key_management_note', models.CharField(blank=True, default='', max_length=300, verbose_name='钥匙管理说明')),
                ('certs_in_place_status', models.CharField(blank=True, choices=[('yes', '√'), ('no', '×'), ('other', '其他')], default='', max_length=10, verbose_name='合格证收纳状态')),
                ('certs_in_place_note', models.CharField(blank=True, default='', max_length=300, verbose_name='合格证收纳说明')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_handover_sessions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_sessions', to='orgs.department', verbose_name='科室')),
            ],
            options={
                'verbose_name': '交班记录',
                'verbose_name_plural': '交班记录',
            },
        ),
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_text', models.CharField(blank=True, default='', max_length=100, verbose_name='科室')),
                ('patient_name', models.CharField(blank=True, default='', max_length=100, verbose_name='姓名')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('surgery_name', models.TextField(blank=True, default='', verbose_name='手术名称')),
                ('special_handover', models.TextField(blank=True, default='', verbose_name='特殊病情交接')),
                ('blood_transfusion_checks', models.CharField(blank=True, choices=[('√', '√'), ('×', '×')], default='', max_length=2, verbose_name='输血前九项')),
                ('pressure_ulcer_assessment', models.CharField(blank=True, choices=[('√', '√'), ('×', '×')], default='', max_length=2, verbose_name='压疮评估单')),
                ('skin_condition', models.CharField(blank=True, choices=[('完整', '完整'), ('缺损', '缺损')], default='', max_length=4, verbose_name='皮肤情况')),
                ('preop_visit', models.CharField(blank=True, choices=[('√', '√'), ('×', '×')], default='', max_length=2, verbose_name='术前访视')),
                ('special_instruments', models.TextField(blank=True, default='', verbose_name='特殊器械准备')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='填报时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_handover_items', to=settings.AUTH_USER_MODEL, verbose_name='填报人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_handover_items', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='handover.handoversession', verbose_name='所属交班')),
            ],
            options={
                'verbose_name': '手术交班条目',
                'verbose_name_plural': '手术交班条目',
            },
        ),
        migrations.AddIndex(
            model_name='handoversession',
            index=models.Index(fields=['department', 'handover_date'], name='handover_ha_departm_a7d226_idx'),
        ),
        migrations.AddConstraint(
            model_name='handoversession',
            constraint=models.UniqueConstraint(fields=('department', 'handover_date'), name='uniq_dept_handover_date'),
        ),
        migrations.AddIndex(
            model_name='handoveritem',
            index=models.Index(fields=['session'], name='handover_ha_session_165aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='handoveritem',
            index=models.Index(fields=['reported_by'], name='handover_ha_reporte_194f3b_idx'),
        ),
    ]
