# Generated by Django 5.1.6 on 2026-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoveritem',
            name='blood_transfusion_checks',
            field=models.CharField(blank=True, choices=[('√', '✅'), ('×', '❌')], default='', max_length=2, verbose_name='输血前九项'),
        ),
        migrations.AlterField(
            model_name='handoveritem',
            name='preop_visit',
            field=models.CharField(blank=True, choices=[('√', '✅'), ('×', '❌')], default='', max_length=2, verbose_name='术前访视'),
        ),
        migrations.AlterField(
            model_name='handoveritem',
            name='pressure_ulcer_assessment',
            field=models.CharField(blank=True, choices=[('√', '✅'), ('×', '❌')], default='', max_length=2, verbose_name='压疮评估单'),
        ),
        migrations.AlterField(
            model_name='handoversession',
            name='bio_monitoring_status',
            field=models.CharField(blank=True, choices=[('yes', '✅'), ('no', '❌'), ('other', '其他')], default='', max_length=10, verbose_name='生物监测状态'),
        ),
        migrations.AlterField(
            model_name='handoversession',
            name='certs_in_place_status',
            field=models.CharField(blank=True, choices=[('yes', '✅'), ('no', '❌'), ('other', '其他')], default='', max_length=10, verbose_name='合格证收纳状态'),
        ),
        migrations.AlterField(
            model_name='handoversession',
            name='crash_cart_status',
            field=models.CharField(blank=True, choices=[('yes', '✅'), ('no', '❌'), ('other', '其他')], default='', max_length=10, verbose_name='急救车状态'),
        ),
        migrations.AlterField(
            model_name='handoversession',
            name='fire_safety_status',
            field=models.CharField(blank=True, choices=[('yes', '✅'), ('no', '❌'), ('other', '其他')], default='', max_length=10, verbose_name='消防安全状态'),
        ),
        migrations.AlterField(
            model_name='handoversession',
            name='key_management_status',
            field=models.CharField(blank=True, choices=[('yes', '✅'), ('no', '❌'), ('other', '其他')], default='', max_length=10, verbose_name='钥匙管理状态'),
        ),
        migrations.AlterField(
            model_name='handoversession',
            name='laminar_flow_running_status',
            field=models.CharField(blank=True, choices=[('yes', '✅'), ('no', '❌'), ('other', '其他')], default='', max_length=10, verbose_name='层流运行状态'),
        ),
        migrations.AlterField(
            model_name='handoversession',
            name='specimen_handover_status',
            field=models.CharField(blank=True, choices=[('yes', '✅'), ('no', '❌'), ('other', '其他')], default='', max_length=10, verbose_name='标本交接状态'),
        ),
    ]
