# Generated by Django 5.1.6 on 2026-04-15 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='科室名称')),
                ('code', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='科室编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '科室',
                'verbose_name_plural': '科室',
            },
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_department', models.CharField(choices=[('admin', '科室管理员'), ('member', '科室成员')], default='member', max_length=20, verbose_name='科室角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='加入时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_department_memberships', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='orgs.department', verbose_name='科室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '科室成员',
                'verbose_name_plural': '科室成员',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='orgs_depart_is_acti_744182_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmember',
            index=models.Index(fields=['department'], name='orgs_depart_departm_da9ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmember',
            index=models.Index(fields=['user'], name='orgs_depart_user_id_4b0bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmember',
            index=models.Index(fields=['department', 'role_in_department'], name='orgs_depart_departm_14129e_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentmember',
            constraint=models.UniqueConstraint(fields=('department', 'user'), name='uniq_department_user'),
        ),
    ]
