# Generated by Django 5.1.6 on 2026-04-22 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='handover_cutoff_time',
            field=models.TimeField(default=datetime.time(8, 10), verbose_name='交班填报截止时间'),
        ),
    ]
