# Generated by Django 5.1.6 on 2026-04-15 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('slug', models.SlugField(blank=True, default='', max_length=220, verbose_name='别名')),
                ('content_html', models.TextField(blank=True, default='', verbose_name='课程内容')),
                ('cover_image_path', models.CharField(blank=True, default='', max_length=500, verbose_name='封面图')),
                ('video_provider', models.CharField(blank=True, default='', max_length=30, verbose_name='视频平台')),
                ('video_url', models.CharField(blank=True, default='', max_length=500, verbose_name='视频链接')),
                ('video_embed_html', models.TextField(blank=True, default='', verbose_name='视频嵌入代码')),
                ('status', models.CharField(default='published', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='orgs.department', verbose_name='科室')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'indexes': [models.Index(fields=['department', 'status'], name='training_co_departm_727940_idx'), models.Index(fields=['slug'], name='training_co_slug_974932_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_url', models.CharField(max_length=1000, verbose_name='文件地址')),
                ('storage_backend', models.CharField(default='local', max_length=30, verbose_name='存储后端')),
                ('object_key', models.CharField(blank=True, default='', max_length=500, verbose_name='对象键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='orgs.department', verbose_name='科室')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '媒体素材',
                'verbose_name_plural': '媒体素材',
                'indexes': [models.Index(fields=['department', 'created_at'], name='training_me_departm_067573_idx')],
            },
        ),
    ]
